name: linkdrop
description: "LinkDrop — share-to-download manager."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  theme:
    path: /Users/ashvinijangid/Desktop/android/theme

  receive_sharing_intent: ^1.8.1
  dio: ^5.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
